plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '9.6.1'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = 'Bob.Bob'
}

tasks.named('shadowJar') {
    archiveBaseName = 'bob'
    archiveClassifier = 'all'
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
}
